#!/bin/bash

# flacman (created by loictlpk/flacman on github) is designed to search flac description for a linux command
# syntax        ==>     ./flacman  <CMD>  <FLAC>


# #### PROGRAM ####
clear

echo "flac is not mandatory AND "
echo "command is an existing bash command"
echo "syntax is ==>    ./flacman <command> <flac>" 

echo 

if [ "$#" -eq 1 ]
then
        man $1

fi
if [ "$#" -gt 1 ]
then
        echo "search description for flac \"-$2\" with command \"$1\""
        for((count=0; count<2; count++)); do
                echo -n "."
                sleep 0.5
        done
        clear

        echo "search description for flac \"-$2\" with command \"$1\""

        for((count=0; count<2; count++)); do
        echo
        done

echo
# ################ COMMAND ################
        ( man $1 | nl | grep -A 1 "\-$2" ) || clear && echo "NO FLAC IS FOUND." 
#
echo
echo

fi