#!/bin/bash

# flagman (created by loictlpk/flagman on github) is designed to search flac description for a linux command
# syntax        ==>     flagman  <CMD>  <FLAG>


# #### PROGRAM ####
clear

echo "flag is not mandatory "
echo "command is an existing bash command"
echo "syntax is ==>    flagman <command> <flag>" 

echo 

if [ "$#" -eq 1 ]
then
        man $1

fi
if [ "$#" -gt 1 ]
then
        echo "search description for flag \"-$2\" with command \"$1\""
        for((count=0; count<2; count++)); do
                echo -n "."
        done
        clear

        echo "search description for flag \"-$2\" with command \"$1\""

        for((count=0; count<2; count++)); do
        echo
        done

echo
# ################ COMMAND ################
        ( man $1 | nl | grep -A 1 "\-$2") || (clear && echo "NO FLAG IS FOUNDED.") 
#

echo

fi
